### ISSUE TITLE
Nothing seems to work?

### ISSUE THREAD

**Issue by DarkAlchy** [Anibaaal/ComfyUI-UX-Nodes#4]
![image](https://github.com/user-attachments/assets/57c5525c-0bb7-47c7-a4b5-aa47477ef0fb)

How do I use your work?

**Comment by Anibaaal** [comment]
Hi. That node is not from this pack, the one you're looking for is called "Save Diffusion Model" for saving only the unet.

**Comment by DarkAlchy** [comment]
I already had that Save Diffusion Model node, so how is yours different?

**Comment by Anibaaal** [comment]
The native comfy node is '**Save Checkpoint**' which is the one you shown on the first post. It can only save model +clip +vae.
The node from this pack '**Save Diffusion Model**' is a modded save checkpoint node that allows saving model without clip and vae.
If you had a node with the same name from other pack, could point me to it so I can change it? 
Unless the feature was added recently to comfy, I couldn't find other node that did this at the time I made it, and Comfy didn't have the a native node for it either.

The bottom node is mine: ![image](https://github.com/user-attachments/assets/b453fad8-2db1-470b-b7fa-a70af278c4b7)

**Comment by DarkAlchy** [comment]
I already had that bottom node is what I was saying, then I grabbed yours hoping it would save in a non diffused state.  I can't find anything they will convert a diffused model so Kohya can use it to train on.  I think peft is what it wants but not sure.
